import Header from '@/components/header'
import * as React from 'react'
import {Suspense} from 'react'
import Loding from '@/components/ui/loding'
import Listcard from './_components/Listcard'
import { Metadata } from 'next'
export const metadata: Metadata = {
  title: '贾雨竹',
  description: 'Generated by create next app',
}


export default function Home() {
  
  return (
 <main>
<Header/>
 <div className='w-[100vh] flex justify-around'>
<Listcard />
 </div>
 </main>
  )
}
