import type { Metadata } from 'next'
import {Zheng} from '@/style/fonts'
import './globals.css'
import '@radix-ui/themes/styles.css'; 
import  SessionProvider  from "@/components/SessionProvider"
import { getServerSession } from 'next-auth'
import { Theme,ThemePanel } from '@radix-ui/themes';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default  async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session= await getServerSession()
  return (
    <html lang="en" >
      <meta name="renderer" content="webkit"/>
<meta name="referrer" content="never"></meta>
      <body >
     <Theme  accentColor="red" grayColor="sand" radius="large" scaling="95%">
     <SessionProvider session={session}>{children}</SessionProvider>
   
     </Theme>
      </body>
    </html>
  )
}
