import Listcard from './_components/Listcard'
import { Metadata } from 'next'
export const metadata: Metadata = {
  title: '其它-贾雨竹',
  description: 'Generated by create next app',
}


export default function Home() {
  
  return (
<Listcard />
  )
}
